openapi: "3.0.0"
info:
  description: >
    # Welcome to the F5 API April challenge

    ## Have Fun!

  version: "1.0.0"
  title: "F5 April API Challenge!"
security:
  - basicHTTPAuthentication: []
servers:
  - url: http://localhost:{port}/{basePath}
    description: localhost service listener
    variables:
      port:
        default: '8183'
      basePath:
        default: 'api/v1'
paths:
    /compute/{id}:
      get:
        summary: 'Retrieve a past compute function calculation by id'
        description: 'Return the result for a past calculation identified by the supplied id'
        tags:
         - Compute
        security:
          - basicHTTPAuthentication: []
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
              format: uuid
        responses:
          200:
            description: Calculation response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MathResponse'
                example:
                  id: 6e8668c6-910d-4fdb-8b8e-757a09c82f16
                  x: 100
                  y: 61
                  operator: add
                  value: 161.0
                  metadata:
                    labels:
                      - key: additions
                        value: '61+100'
                      - key: math
                        value: basic
                    annotations:
                      - key: costmonth
                        value: April
                      - key: costyear
                        value: 2022
          400:
            description: Client error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 400
                  message: query request included a request body
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 401
                  message: Unauthorized
          404:
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 404
                  message: Not found
          500:
            description: Service error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 500
                  message: compute environment not available
      delete:
        summary: 'Delete a past compute function calculation by id'
        description: 'Delete the past calculation identified by the supplied id'
        tags:
         - Compute
        security:
          - basicHTTPAuthentication: []
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
              format: uuid
        responses:
          202:
            description: Deleted
          400:
            description: Client error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 400
                  message: delete request included content body
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 401
                  message: Unauthorized
          404:
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 404
                  message: Not found
          500:
            description: Service error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 500
                  message: database error
    /compute:
      get:
        summary: 'Retrieve past compute calculations optionally filtered by label selection'
        description: 'Get past compute calculations. Returns past calculations or a filtered list based on basic label selection supplied by query parameters.'
        tags:
         - Compute
        security:
          - basicHTTPAuthentication: []
        parameters:
          - in: query
            name: label
            description: label to use for filtering
            required: false
            schema:
              type: string
              maxLength: 64
          - in: query
            name: match
            description: the match form for the label
            required: false
            schema:
              type: string
              enum:
                - equals
                - notequals
                - in
                - notin
          - in: query
            name: value
            description: match string
            required: false
            schema:
              type: string
              maxLength: 64
        responses:
          200:
            description: List of calculation responses
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/MathResponse'
                example:
                  - id: 6e8668c6-910d-4fdb-8b8e-757a09c82f16
                    x: 61
                    y: 100
                    operation: add
                    value: 161.0
                    metadata:
                    labels:
                      - key: additions
                        value: '61+100'
                      - key: math
                        value: basic
                    annotations:
                      - key: costmonth
                        value: April
                      - key: costyear
                        value: 2022
                  - id: 57855074-9556-4559-9c87-b68b41615164
                    x: 2001
                    y: 206
                    operation: divide
                    value: 9.7
                    metadata:
                    labels:
                      - key: divisions
                        value: '2001/206'
                      - key: math
                        value: basic
                    annotations:
                      - key: costmonth
                        value: April
                      - key: costyear
                        value: 2022
                  - id: f4d0b7d5-2c6b-4802-9d56-84b2224eb25c
                    x: 22
                    y: 23
                    operation: subtract
                    value: -1.0
                    metadata:
                    labels:
                      - key: subtractions
                        value: '22-23'
                      - key: math
                        value: basic
                    annotations:
                      - key: costmonth
                        value: April
                      - key: costyear
                        value: 2022
          400:
            description: Client error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 400
                  message: query request included a request body
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 401
                  message: Unauthorized
          404:
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 404
                  message: Not found
          500:
            description: Service error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 500
                  message: datbase error
      post:
        summary: Request a new calculation
        description: Request the service make and store the supplied calculation
        tags:
         - Compute
        security:
          - basicHTTPAuthentication: []
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MathRequest'
              example:
                x: 61
                y: 161
                operation: add
                metadata:
                  labels:
                    - key: additions
                      value: '61+100'
                    - key: math
                      value: basic
                  annotations:
                    - key: costmonth
                      value: April
                    - key: costyear
                      value: 2022
        responses:
          200:
            description: Calculation response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MathResponse'
                example:
                  id: 6e8668c6-910d-4fdb-8b8e-757a09c82f16
                  x: 61
                  y: 100
                  operation: add
                  value: 161.0
                  metadata:
                    labels:
                      - key: additions
                        value: '61+100'
                      - key: math
                        value: basic
                    annotations:
                      - key: costmonth
                        value: April
                      - key: costyear
                        value: 2022
          400:
            description: Client error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 400
                  message: invalid compute - divide by zero
          401:
            description: Unauthorized
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 401
                  message: Unauthorized
          404:
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 404
                  message: Not found
          500:
            description: Service error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                example:
                  code: 500
                  message: compute environment is unavailable
components:
  securitySchemes:
    basicHTTPAuthentication:
      type: http
      scheme: basic
  schemas:
    ErrorResponse:
      type: object
      description: Reponse object for an error
      properties:
        code:
          type: integer
          format: int32
          minimum: 400
          maximum: 599
        message:
          type: string
    KeyValue:
      type: object
      description: KeyValue type
      properties:
        key:
          type: string
          maxLength: 128
          minLength: 2
          pattern: '^[A-Za-z]'
        value:
          type: string
          maxLength: 128
          minLength: 2
    MetadataType:
      type: object
      description: metadata for the request operation
      title: MetadataType
      properties:
        annotations:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
        labels:
          type: array
          items:
            $ref: '#/components/schemas/KeyValue'
    MathRequest:
      type: object
      description: Request object for a math function request
      title: MathRequest
      properties:
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
        operation:
          type: string
          enum:
            - add
            - subtract
            - multiply
            - divide
        metadata:
          $ref: '#/components/schemas/MetadataType'
    MathResponse:
      type: object
      description: Response object to a math function request
      properties:
        id:
          type: string
          format: uuid
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
        operation:
          type: string
        value:
          type: number
          format: float
        metadata:
          $ref: '#/components/schemas/MetadataType'
